### ISSUE TITLE
Not a real issue 

### ISSUE THREAD

**Issue by clonefish0** [carlospolop/hacktricks#106]
Is there a way to have a port open for the internet on a domain? 

Example port 666 - domain: clonefish00.whatever? So I can sent to the specific users the link and they can login with their access ? Less then 5 users are planned

**Comment by carlospolop** [comment]
Hi @clonefish0,
If you are looking people to access a port with the browser you can use something like `http://clonefish00.whatever:666`.
If you didn't mean that, then I'm not understanding the question.
Also, github issues isn't the correct place to ask generic IT/cybersecurity questions. Please, feel free to ask it in the telegram group: https://t.me/peass

**Comment by clonefish0** [comment]
The telegram is private :/
