### ISSUE TITLE
Add the link to the website in the *About* Section 

### ISSUE THREAD

**Issue by clem9669** [carlospolop/hacktricks#13]
Add the link to the website instead of this description : 

`No description, website, or topics provided.`

<img width="304" alt="Screenshot 2020-09-05 at 20 15 13" src="https://user-images.githubusercontent.com/18504086/92311121-83a4f880-efb4-11ea-8d62-5dffdf1d7008.png">

**Comment by carlospolop** [comment]
Hey @clem9669,

Could you explain yourself more?

**Comment by clem9669** [comment]
Hey,

If you want to visit the GitHub from the website, you can because you have a link and icon for modifications etc ...
But if you are on the GitHub and want to visit the website there is not link to it.

Github repo have a field that you have to fiel to add the link to the website project: https://book.hacktricks.xyz

Cheers 😃

**Comment by carlospolop** [comment]
oh, haha yeah mate, I forgot to put that on github, thanks mate!
