### ISSUE TITLE
Add recent PE 

### ISSUE THREAD

**Issue by clem9669** [carlospolop/hacktricks#143]
It is possible to read SYSTEM SAM SECURITY on fully patch windows 10 & 11.

https://mobile.twitter.com/gentilkiwi/status/1417229454305267714

**Comment by carlospolop** [comment]
Hey @clem9669!
At the moment I'm very focused on MacOS and I haven't had time to add all that is happening with Windows...
May I ask you to submit a PR with this vuln (and others like printnightmare if you wish?)

**Comment by ghost-ng** [comment]
FYI @clem9669 - this script checks for those vulns, consider looking through it
https://github.com/itm4n/PrivescCheck

**Comment by carlospolop** [comment]
Is this still a thing? or should we close the issue?
