### ISSUE TITLE
Add a privesc method: Docker Socket

### ISSUE THREAD

**Issue by clem9669** [carlospolop/hacktricks#16]
Add a privesc method of abusing open Docker sockets

Read more :

[https://securityboulevard.com/2019/02/abusing-docker-api-socket/](https://securityboulevard.com/2019/02/abusing-docker-api-socket/)

**Comment by carlospolop** [comment]
Hi mate,
I have been busy these days (and still are), but I will take a look and add the tricks asap

**Comment by clem9669** [comment]
No problem, it was if someone saw my issue and wanted to push before i get the time to do it 😉

**Comment by carlospolop** [comment]
Hi mate,
I have finally added this information inside the pentesting docker page! Happy new year!
