### ISSUE TITLE
Two files one name (for some tools)

### ISSUE THREAD

**Issue by cmprmsd** [carlospolop/hacktricks#215]
Heya,

I noticed Syncthing complaining about file conflicts and it seems you have two files for the same topic which looks like an oversight:

```
./hacktricks/pentesting/pentesting-SAP.md
./hacktricks/pentesting/pentesting-sap.md
```
I guess you can delete the outdated one :)

**Comment by carlospolop** [comment]
Thanks! Did you find more issues like that?

**Comment by cmprmsd** [comment]
This was the only issue I noticed 😊 thanks for merging!
