### ISSUE TITLE
Correction to Initiating WinRM Session section

### ISSUE THREAD

**Issue by ClutchTech** [carlospolop/hacktricks#258]
It appears "attack machine" and "victim" are reversed in this section. Enable-PSRemoting is used to configure a computer to recieve powershell commands, not to send them. Although attacks do vary, it's less likely an attacker would need to setup the attacking machine with powershell remote enabled.

**Comment by carlospolop** [comment]
Hi @ClutchTech ,
could you submit a PR with these changes please?

**Comment by carlospolop** [comment]
Thanks for your PR!
