### ISSUE TITLE
strings-per-processes

### ISSUE THREAD

**Issue by 4v4n965h** [carlospolop/hacktricks#270]
forensics/basic-forensic-methodology/memory-dump-analysis/volatility-examples.md

in strings-per-processes theres "s" missing 
./vol.py -f /tmp/file.dmp windows.strings.Strings --string-file /tmp/strings.txt

mod > ./vol.py -f /tmp/file.dmp windows.strings.Strings --strings-file /tmp/strings.txt

**Comment by carlospolop** [comment]
Hi @4v4n965h,

Thank for reporting this, It's fixed now.
Next time consider submitting a pull request if you want!
