### ISSUE TITLE
Add Japanese translation

### ISSUE THREAD

**Issue by wacker928** [carlospolop/hacktricks#321]
@carlospolop Hello! Huge thanks to you, Hacktrick has become the de-facto reference platform for penetration testing.

I've been wanting to ask, if you are thinking of hosting Hacktrick in multiple languages, such as Japanese? Many penetration testers in Japan also rely on Hacktrick for knowledge of penetration testing. 

If you agree with this, let me know and I'll start translating the document :))

**Comment by carlospolop** [comment]
Hi @wacker928,
I have thought about using APIs to traduce hacktricks to other languages for so long... but I just don't have the time.
If you want to traduce it manually to Japanese feel free and I ca host it in a subdomain of hacktricks if you want.
But it would probably be easier to use APIs such as deepl to translate to different languages.
Let me know what you do!

**Comment by tanaka-geek** [comment]
@carlospolop, 
If you can host it in a subdomain of hacktricks, that'd be great! 

I'll be using DeepL to translate the documents, but I'll manually go through them to fix some mis-translations and correct the context in the language.

I'll contact you again once the translation work is done.

Thanks a lot!

**Comment by carlospolop** [comment]
cool!
Also, if you create a script to send data to deepl to traduce, please, share the script so I can use it to traduce hacktricks to other languages!

**Comment by carlospolop** [comment]
Hi @wacker928,
any updates on this?

**Comment by carlospolop** [comment]
Hi @wacker928,
Any updates on this?

**Comment by carlospolop** [comment]
Hi @wacker928,
Any updates on this?

**Comment by tanaka-geek** [comment]
> Hi @wacker928, any updates on this?

@carlospolop Hello! Thanks for giving me heads up, 
I'm still translating the remaining of the documents, will need a few more couple weeks.
I am using DeepL to traduce by the way, manually re-writing the markdown docs (takes a bit of time haha)

**Comment by carlospolop** [comment]
Any news about this @wacker928 ??

**Comment by takahiro-prog** [comment]
Hi, @carlospolop,
I would like to help with the Japanese translation of Hacktricks.
Is there any specific area where I should contribute? 
By the way, I'm neither a security expert nor an experienced OSS contributor, but I would like to assist with translation work that I believe I can handle. 
Looking forward to your response. 
Apologies if my this comments were incorrect.

**Comment by carlospolop** [comment]
Translated in https://book.hacktricks.xyz/v/jp/welcome/readme
It was translated automatically using gpt-3.5-turbo
Take a look and let me know your thoughts
