### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [carlospolop/hacktricks#43]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the document under the [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/) license so that others are encouraged to contribute changes back to your project.

**Comment by carlospolop** [comment]
Hi @TechnologyClassroom,

Thank you for the suggestion. It's actually a good idea.
Could you please send a push request adding the LICENSE file to the repo?

**Comment by TechnologyClassroom** [comment]
@carlospolop Will do later today!
