### ISSUE TITLE
MQTT duplicate

### ISSUE THREAD

**Issue by noraj** [carlospolop/hacktricks#433]
I saw my change made in https://github.com/carlospolop/hacktricks/pull/318 was not reflected to https://book.hacktricks.xyz/network-services-pentesting/1883-pentesting-mqtt-mosquitto.

That's because I PRed to [pentesting/1883-8883-pentesting-mqtt-mosquitto.md](https://github.com/carlospolop/hacktricks/blob/master/pentesting/1883-8883-pentesting-mqtt-mosquitto.md) which is not displayed on the website. Only the duplicated page [network-services-pentesting/1883-pentesting-mqtt-mosquitto.md](https://github.com/carlospolop/hacktricks/blob/master/network-services-pentesting/1883-pentesting-mqtt-mosquitto.md).

Gitbook seems to generate a lot of mess and duplicate files 😂  

I suggest:

- Removing `network-services-pentesting/1883-pentesting-mqtt-mosquitto.md`
- Moving `pentesting/1883-8883-pentesting-mqtt-mosquitto.md` to `network-services-pentesting/1883-8883-pentesting-mqtt-mosquitto.md`

**Comment by carlospolop** [comment]
hi @noraj , could you send a PR?

**Comment by noraj** [comment]
soon
