### ISSUE TITLE
139,445 - Pentesting SMB

### ISSUE THREAD

**Issue by maxkleinke** [carlospolop/hacktricks#5]
Hey there,

I just ran into something that would be probably nice to have as information to pentest SMB shares:

I'm actually getting restricted from displaying available network shares on a windows machine, which first made me believe there aren't any open shares. After researching though (reading the section about SMB of the Network Security Assessment, 3rd Edition book) I found the names of common shares and tested them manually, which actually lead to successfully connecting to an exposed share.

So my enhancement would be to add a section at "139,445 - Pentesting SMB", that encourages to manually test for common open shares regardless if they are displayed or not.

Common share names for windows described in the book are

> IPC$
> C$
> D$
> ADMIN$
> PRINT$
> FAX$
> SYSVOL
> NETLOGON

I used the following command to manually test the shares

> smbclient -U '%' -N \\\\\\\\IP\\\\SHARE

Please let me know what you think and thank you for such an awesome resourse.

**Comment by carlospolop** [comment]
Hi mate!
That sounds cool, thank you for sharing your trick.
Do you want me to add it, or would you like to submit a pull request and appear as collaborator?

**Comment by 0xalwayslucky** [comment]
totally can create one!

probably gonna submit the request tomorrow

**Comment by carlospolop** [comment]
Perfect mate!

Submit it and I will accept it.
Thanks!
