### ISSUE TITLE
Link for Docker container escape points to a non-existing page

### ISSUE THREAD

**Issue by 0xsyr0** [carlospolop/hacktricks#502]
This one needs to be updated i think.

`Docker socket /var/run/docker.sock is writable (https://book.hacktricks.xyz/linux-unix/privilege-escalation#writable-docker-socket)`

With maybe this one `https://book.hacktricks.xyz/linux-hardening/privilege-escalation/docker-breakout/abusing-docker-socket-for-privilege-escalation`. Maybe it was moved.

**Comment by ghost** [comment]
Hi @0xsyr0,

Is this Issue meant for Linpeas? If so, please submit the Issue at carlospolop / PEASS-ng.

Thanks.

**Comment by 0xsyr0** [comment]
Hi oddrabbit,

thank you for your reply. Of course, my bad, i close this one and opened it at PEASS-ng.

Regards,
syro
