### ISSUE TITLE
Add capture packets remotely with Wireshark and tcpdump over ssh

### ISSUE THREAD

**Issue by manesec** [carlospolop/hacktricks#508]
Hi Carlos,

Would you like to add tcpdump over ssh in [Pentesting Network](https://book.hacktricks.xyz/generic-methodologies-and-resources/pentesting-network#tcpdump)?

Sometimes remote machines without wireshark become very useful :)

You can test it in Lightweight (From HTB Machine).

```bash
ssh user@remote_ip /sbin/tcpdump -i ens160 -U -s0 -w - | wireshark -k -i -

# exclude ssh traffic
ssh user@remote_ip /sbin/tcpdump -i ens160 -U -s0 -w - 'port not 22' | wireshark -k -i -
```
Thank you for your hacktricks.

**Comment by ghost** [comment]
Hi @carlospolop,

I have just added the Pull Request #539 for this Issue. Please merge if acceptable to you.

Thanks.
