### ISSUE TITLE
Method to read the material offline (ebook or PDF)

### ISSUE THREAD

**Issue by gkwhite** [carlospolop/hacktricks#60]
I really enjoy this site and the information you've created.  I tried a number of ways to scrape the site to a PDF or ebook for offline consumption, but none of them worked or they looked really bad.  :)

**Comment by carlospolop** [comment]
Hi @gkwhite,
I completely agree with you, but just as you, I don't know how to create a well organized PDF from hacktricks website for free.
I have assigned the label `help wanted` for this issue and I will leave it open. Lets see if someone else find the way to download hacktricks correctly.

**Comment by clem9669** [comment]
If it helps: https://docs.gitbook.com/features/pdf-export

**Comment by carlospolop** [comment]
Thanks @clem9669, but thats a premium feature.
I currently use a free Gitbook account, so I cannot export the book as PDF... We need to search other alternatives, or beg gitbook to enable this feature for free

**Comment by rcautela90** [comment]
Are you just looking for the code itself in a .pdf so you can copy and paste, or do you want information from the subsequent sites condensed into one document?

**Comment by clem9669** [comment]
I missed the fact that was a premium feature.
Found an alternative from https://www.forgebox.io/view/gitbook-exporter:
A CommandBox module for converting a GitBook into a PDF/eBook. This is an open source community module and not endorsed or affiliated with GitBook.

**Comment by carlospolop** [comment]
Hi guys,

Thank yo very much @clem9669, that worked.
Please, read here the guide to obtain a PDF copy of HACKTRICKS: https://github.com/carlospolop/hacktricks/issues/66
Let me know if you don't agree with the rules mentioned in that guide.
@clem9669 as you have sent several PR, feel free to ask for a PDF copy of HACKTRICKS if you want.

Just as reminder for me for the future I needed to give 8GB of memory to the VM and use the following params inside CommandBox: 
```
start minHeapSize=4096 heapSize=8192
config set verboseErrors=true
gitbook export --PDF
```
