### ISSUE TITLE
Is there a good way to handle redirects?

### ISSUE THREAD

**Issue by kingthorin** [carlospolop/hacktricks#626]
I just noticed that https://github.com/carlospolop/hacktricks/blob/master/pentesting-web/xslt-server-side-injection-extensible-stylesheet-languaje-transformations.md has a typo in the file name, however I was wondering if there was a preferred mechanism for handling redirects in case anyone already has it bookmarked or deep linked?

`languaje` ➡ `language`

**Comment by carlospolop** [comment]
gitbook does that automatically, no worries.
Just changed it
