### ISSUE TITLE
Wrong description on getting werkzeug pin

### ISSUE THREAD

**Issue by Kaiziron** [carlospolop/hacktricks#643]
```
get_machine_id() concatenate the values in /etc/machine-id , /proc/sys/kernel/random/boot_id and first line of /proc/self/cgroup after the last slash (/).
```
If there is value in /etc/machine-id, it will break from the loop and would not read /proc/sys/kernel/random/boot_id at all
It concatenate either /etc/machine-id with /proc/self/cgroup or /proc/sys/kernel/random/boot_id with /proc/self/cgroup

https://github.com/pallets/werkzeug/blob/main/src/werkzeug/debug/__init__.py#L58-L67

**Comment by carlospolop** [comment]
was this already fixed or could you submit a PR to fix this?
