### ISSUE TITLE
HACKTRICKS DEAD

### ISSUE THREAD

**Issue by h4ckerlite** [carlospolop/hacktricks#810]
hacktricks esta muerto, no se puede acceder al dominio
![image](https://github.com/carlospolop/hacktricks/assets/70925909/4e589088-4587-4910-aede-fe798c63bb82)

**Comment by carlospolop** [comment]
It's working, check your connection
![image](https://github.com/carlospolop/hacktricks/assets/17181413/023c4c1a-7ff2-439b-a630-d18c3f87e01c)
