### ISSUE TITLE
Links incorrectly separated

### ISSUE THREAD

**Issue by SlickNutter** [carlospolop/hacktricks#88]
In https://github.com/carlospolop/hacktricks/blob/master/mobile-apps-pentesting/android-app-pentesting/README.md#owasp there are 2 links marked as one:
- https://github.com/OWASP/owasp-mstg
- https://mobile-security.gitbook.io/mobile-security-testing-guide/ios-testing-guide/0x06g-testing-network-communication

Could do a pull request later today in the evening, if preferred.

**Comment by carlospolop** [comment]
done! thanks mate!
