### ISSUE TITLE
In Abusing DAC_Override Capability, syntax error in code.

### ISSUE THREAD

**Issue by emalp** [carlospolop/hacktricks#93]
Line 35 in https://book.hacktricks.xyz/linux-unix/privilege-escalation/linux-capabilities#cap_dac_override docker breakout, the code has a simple syntax error.
The error is caused because there is no function definition before the opening braces. The missing function is find_handle.

Fix: Append
`int find_handle(int bfd, const char *path, const struct my_file_handle *ih, struct my_file_handle *oh) `
before the '{' in line 35.

**Comment by carlospolop** [comment]
Nice one! thanks mate! it's now fixed
