### ISSUE TITLE
lxc lxd build alpine image method 2 no working

### ISSUE THREAD

**Issue by vivienicepig** [carlospolop/hacktricks#97]
do not how to pull...so write it here

file:
hacktricks/linux-unix/privilege-escalation/interesting-groups-linux-pe/lxd-privilege-escalation.md 

in method2:
latest alpine image does not contain this file ==> rootfs/usr/share/alpine-mirrors/Mirrors.txt

walkaround:
edit build_alpine file on line 22
origin => yaml_path="latest_stable/releases/$apk_arch/latest-releases.yaml"
new => yaml_path="v3.8/releases/$apk_arch/latest-releases.yaml"

**Comment by clem9669** [comment]
Hi @vivienicepig ! 

Do you have a link from the editor or a link to the documentation that can be use as a reference ?

Cheers 😃

**Comment by carlospolop** [comment]
Hi @vivienicepig,

That worked to fix also the `Failed to install rootfs` issue.
I have updated hacktricks, thanks.
